export const MOODS = [
  "calm",
  "melancholy",
  "cozy",
  "nostalgic",
  "fantasy",
  "dreamy",
];

export const INSTR = [
  "rhodes",
  "nylon guitar",
  "upright bass",
  "pads",
  "electric piano",
  "piano",
  "clean electric guitar",
  "airy pads",
  "vinyl sounds",
  "acoustic guitar",
  "violin",
  "cello",
  "flute",
  "saxophone",
  "trumpet",
  "french horn",
  "synth lead",
  "string squeaks",
  "key clicks",
  "breath noise",
  "harp",
  "lute",
  "pan flute",
  "brush kit",
  "shaker",
  "tambourine",
  "808 sub-kick",
  "wurlitzer",
  "celesta",
  "music box",
  "glockenspiel",
  "vibraphone",
  "marimba",
  "muted electric guitar",
  "muted trumpet",
  "clarinet",
  "oboe",
  "field recordings",
  "synth plucks",
  "timpani",
  "pipe organ",
  "choir",
];
